  
#BSUB -W 24:00                    
#BSUB -o /rsrch5/scratch/biostatistics/swang23/Staggering/TableS12/Sim_codes/Strict.Stagger.U70_sim.%J.%I
#BSUB -e /rsrch5/scratch/biostatistics/swang23/Staggering/TableS12/Sim_codes/Strict.Stagger.U70_sim.%J.%I
#BSUB -cwd /rsrch5/scratch/biostatistics/swang23/Staggering/TableS12/Sim_codes
#BSUB -q medium
#BSUB -u 
#BSUB -n 6
#BSUB -M 16
#BSUB -R rusage[mem=16]
#BSUB -B
#BSUB -N 
module load R/4.3.1
Rscript Run.Sim.Strict.Stagger.U70.R ${LSB_JOBINDEX} 

# The $LSB_JOBINDEX will be assigned the value of the job array index.
echo "This job has been assigned the array index:"
echo $LSB_JOBINDEX

# bsub -J "Strict.Stagger.U70_sim[1-300]" < ./Strict.Stagger.simu.test.U70.lsf